In [36]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
import seaborn as sns
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

data = sns.load_dataset("iris")

data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [41]:
lb = LabelEncoder()
data_new = data
data_new["species"] = lb.fit_transform(data_new["species"])

data_new.head()

X = data_new[["sepal_length","petal_length"]].copy()
y = data_new["species"].copy()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

LR = LogisticRegression(multi_class="multinomial")

LR.fit(X_train,y_train)
y_test_predict = LR.predict(X_test)

from sklearn.metrics import confusion_matrix
from sklearn import metrics

confusionMatrix = confusion_matrix(y_test,y_test_predict)
confusionMatrix

acc = metrics.accuracy_score(y_test,y_test_predict)

print(acc)

y_pred_proba = LR.predict_proba(X_test)

y_pred_proba

1.0


array([[2.10776420e-03, 6.35446620e-01, 3.62445616e-01],
       [9.03007811e-01, 9.69909084e-02, 1.28065412e-06],
       [7.05620062e-09, 1.95438578e-03, 9.98045607e-01],
       [4.57294939e-03, 7.67693145e-01, 2.27733905e-01],
       [1.01998809e-03, 6.77830936e-01, 3.21149076e-01],
       [9.51186557e-01, 4.88130508e-02, 3.92452396e-07],
       [7.29765342e-02, 9.13280861e-01, 1.37426043e-02],
       [2.80684889e-04, 4.32034189e-01, 5.67685126e-01],
       [4.06121882e-03, 7.94604734e-01, 2.01334047e-01],
       [2.98509184e-02, 9.34121494e-01, 3.60275873e-02],
       [3.14950868e-04, 3.56890439e-01, 6.42794610e-01],
       [9.75482503e-01, 2.45172775e-02, 2.19313206e-07],
       [9.67768466e-01, 3.22314188e-02, 1.15115221e-07],
       [9.66187437e-01, 3.38121595e-02, 4.03189147e-07],
       [9.60811588e-01, 3.91880131e-02, 3.99130773e-07],
       [1.91005329e-03, 6.71129029e-01, 3.26960918e-01],
       [6.09365061e-06, 4.09938569e-02, 9.59000049e-01],
       [3.44088685e-02, 9.23873

In [53]:
import numpy as np
query = np.array([[3.6,2.3]])

#Predictns = LR.predict(query)
X_test.shape

query
LR.predict_proba(query)
#LR.predict(query)

C:\Users\RajnarayanSahu\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[9.09836906e-01, 9.01070001e-02, 5.60942148e-05]])

In [68]:
import warnings
warnings.filterwarnings("ignore")

X_new = data.iloc[:,0:4]
y_new = data.iloc[:,-1]

X_new_train,X_new_test,y_new_train,y_new_test = train_test_split(X_new,y_new,test_size=0.2,random_state=42)

LR.fit(X_new_train,y_new_train)
y_new_pred = LR.predict(X_new_test)

Acc_new = metrics.accuracy_score(y_new_test,y_new_pred)

print(Acc_new)

print(metrics.confusion_matrix(y_new_test,y_new_pred))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
